[pytest]
addopts = --headed --browser chromium --screenshot on --html=report.html --self-contained-html
testpaths = tests
pythonpath = .
markers =
    smoke: Smoke tests
    sanity: Sanity tests
    regression: Regression tests